package com.example.ui

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.os.Build
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.Paper
import java.io.File
import java.io.FileOutputStream
import java.io.IOException

object ExportUtils {

    /**
     * Generates a fully formatted, standard IEEE/Scientific LaTeX document from [Paper].
     */
    fun generateLatexString(paper: Paper): String {
        val docClass = when {
            paper.type.contains("Conference", ignoreCase = true) -> "\\documentclass[conference]{IEEEtran}"
            paper.type.contains("Journal", ignoreCase = true) -> "\\documentclass[journal]{IEEEtran}"
            paper.type.contains("Springer", ignoreCase = true) -> "\\documentclass{llncs}"
            paper.type.contains("Elsevier", ignoreCase = true) -> "\\documentclass[review]{elsarticle}"
            else -> "\\documentclass[12pt]{article}"
        }

        fun escapeLatex(text: String): String {
            return text
                .replace("\\", "\\backslash{}")
                .replace("_", "\\_")
                .replace("%", "\\%")
                .replace("&", "\\&")
                .replace("#", "\\#")
                .replace("{", "\\{")
                .replace("}", "\\}")
                .replace("~", "\\textasciitilde{}")
                .replace("^", "\\textasciicircum{}")
        }

        val escapedTitle = escapeLatex(paper.title.ifBlank { "Manuscrito de Investigación" })
        val escapedField = escapeLatex(paper.fieldOfStudy.ifBlank { "Campo Científico Sin Especificar" })
        val escapedKeywords = escapeLatex(paper.keywords.ifBlank { "Simulación, Optimización, Automatización" })

        return buildString {
            appendLine("%% LaTeX Generated by Generador Científico de Papers Pro %%")
            appendLine(docClass)
            appendLine()
            appendLine("\\usepackage[utf8]{inputenc}")
            appendLine("\\usepackage{amsmath}")
            appendLine("\\usepackage{amssymb}")
            appendLine("\\usepackage{amsfonts}")
            appendLine("\\usepackage{graphicx}")
            appendLine("\\usepackage{booktabs}")
            appendLine("\\usepackage{hyperref}")
            appendLine()
            appendLine("\\title{$escapedTitle}")
            appendLine("\\author{Autor Principal \\\\ \\small $escapedField}")
            appendLine("\\date{\\today}")
            appendLine()
            appendLine("\\begin{document}")
            appendLine()
            appendLine("\\maketitle")
            appendLine()
            appendLine("\\begin{abstract}")
            appendLine(paper.abstractText.ifBlank { "Este manuscrito carece de un resumen formal por el momento." })
            appendLine("\\end{abstract}")
            appendLine()
            if (paper.keywords.isNotBlank()) {
                if (docClass.contains("IEEEtran")) {
                    appendLine("\\begin{IEEEkeywords}")
                    appendLine(escapedKeywords)
                    appendLine("\\end{IEEEkeywords}")
                } else {
                    appendLine("\\noindent\\textbf{Keywords---} $escapedKeywords")
                    appendLine()
                }
            }
            appendLine()
            appendLine("\\section{Introducción}")
            appendLine(paper.introduction.ifBlank { "Reemplace este marcador de posición con su introducción formal de investigación." })
            appendLine()
            appendLine("\\section{Metodología}")
            appendLine(paper.methodology.ifBlank { "Reemplace este marcador de posición con detalles sobre su metodología, algoritmos o ecuaciones." })
            appendLine()
            appendLine("\\section{Resultados y Evaluación}")
            appendLine(paper.resultsAndEvaluation.ifBlank { "Reemplace este marcador de posición con los resultados del experimento o hallazgos cuantitativos." })
            appendLine()
            appendLine("\\section{Conclusiones}")
            appendLine(paper.conclusion.ifBlank { "Resuma el impacto práctico e hipótesis validadas en esta sección de conclusiones." })
            appendLine()
            appendLine("\\begin{thebibliography}{99}")
            if (paper.referencesText.isNotBlank()) {
                val refs = paper.referencesText.split("\n").filter { it.isNotBlank() }
                refs.forEachIndexed { index, ref ->
                    appendLine("\\bibitem{ref${index + 1}}")
                    appendLine(escapeLatex(ref))
                }
            } else {
                appendLine("\\bibitem{ref1}")
                appendLine("Referencia bibliográfica academica general.")
            }
            appendLine("\\end{thebibliography}")
            appendLine()
            appendLine("\\end{document}")
        }
    }

    /**
     * Saves paper LaTeX string into cache and shares it via chooser.
     */
    fun shareLatex(context: Context, paper: Paper) {
        val latexContent = generateLatexString(paper)
        val safeFileName = "Paper_${paper.id}_" + (paper.title.take(15).replace("[^a-zA-Z0-9]".toRegex(), "_")) + ".tex"
        
        try {
            val cacheFile = File(context.cacheDir, safeFileName)
            FileOutputStream(cacheFile).use { out ->
                out.write(latexContent.toByteArray())
            }

            val fileUri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                cacheFile
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_STREAM, fileUri)
                putExtra(Intent.EXTRA_SUBJECT, "Exportación LaTeX: ${paper.title}")
                putExtra(Intent.EXTRA_TEXT, "Adjunto documento científico en formato LaTeX (.tex) de la investigación: '${paper.title}'")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            context.startActivity(Intent.createChooser(shareIntent, "Compartir LaTeX (.tex)"))
        } catch (e: Exception) {
            Toast.makeText(context, "Error exportando LaTeX: ${e.message}", Toast.LENGTH_LONG).show()
        }
    }

    /**
     * Renders [Paper] as a highly styled scholarly PDF using native Android Canvas
     * with standard Letter bounds in Serif style, dynamic word-wrapping metadata, and multiclass formatting.
     */
    fun sharePdf(context: Context, paper: Paper) {
        val pdfDocument = PdfDocument()

        // Page setup: Standard Letter size is 612 x 792 postscript points
        val pageWidth = 612
        val pageHeight = 792
        val margin = 54f // 0.75 in
        val contentWidth = pageWidth - (margin * 2)

        // Paint components
        val textPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.BLACK
            typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
            textSize = 9.5f
        }

        val titlePaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.BLACK
            typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
            textSize = 17f
        }

        val subtitlePaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.DKGRAY
            typeface = Typeface.create(Typeface.SERIF, Typeface.ITALIC)
            textSize = 10f
        }

        val sectionPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.rgb(0, 97, 164) // Academic blue ScholarBlue
            typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
            textSize = 11.5f
        }

        val boldLabelPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.BLACK
            typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
            textSize = 9.5f
        }

        val headerFooterPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.GRAY
            typeface = Typeface.create(Typeface.SERIF, Typeface.ITALIC)
            textSize = 8f
        }

        val decoratorPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.LTGRAY
            strokeWidth = 0.5f
            style = Paint.Style.STROKE
        }

        var pageNumber = 1
        var currentY = margin

        // Initialize helper to create pages on demand
        var pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas

        // Function to draw running header & footer
        fun drawHeaderAndFooter(canvas: Canvas, pageNum: Int) {
            // Draw running header starting from page 2
            if (pageNum > 1) {
                val headerText = if (paper.title.length > 50) "${paper.title.take(47)}..." else paper.title
                canvas.drawText(headerText.uppercase(), margin, margin - 15f, headerFooterPaint)
                canvas.drawLine(margin, margin - 10f, pageWidth - margin, margin - 10f, decoratorPaint)
            }
            // Draw footer page number
            val footerText = "Manuscrito Científico - Página $pageNum"
            val footerX = (pageWidth - headerFooterPaint.measureText(footerText)) / 2f
            canvas.drawText(footerText, footerX, pageHeight - 25f, headerFooterPaint)
        }

        // Standardized pagination checker
        fun checkPageOverflow(elementHeight: Float): Canvas {
            if (currentY + elementHeight > pageHeight - margin - 20f) {
                // Seal current page
                drawHeaderAndFooter(canvas, pageNumber)
                pdfDocument.finishPage(page)

                // Start new page
                pageNumber++
                pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
                page = pdfDocument.startPage(pageInfo)
                canvas = page.canvas
                currentY = margin + 15f // leaving clean room after header
            }
            return canvas
        }

        // Draw a text layout using StaticLayout to support wrapping
        fun drawWrappedText(text: String, paint: TextPaint, width: Int, leftPadding: Float = margin, spacingMultiplier: Float = 1.15f) {
            val paragraphs = text.split("\n")
            for (pText in paragraphs) {
                if (pText.isBlank()) {
                    currentY += 6f // paragraph gap
                    continue
                }
                
                val staticLayout = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                    StaticLayout.Builder.obtain(pText, 0, pText.length, paint, width)
                        .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                        .setLineSpacing(0f, spacingMultiplier)
                        .setIncludePad(false)
                        .build()
                } else {
                    @Suppress("DEPRECATION")
                    StaticLayout(pText, paint, width, Layout.Alignment.ALIGN_NORMAL, spacingMultiplier, 0f, false)
                }

                val lineCount = staticLayout.lineCount
                for (i in 0 until lineCount) {
                    val start = staticLayout.getLineStart(i)
                    val end = staticLayout.getLineEnd(i)
                    val lineStr = pText.substring(start, end).trimEnd('\n', '\r')
                    
                    val lineHeight = staticLayout.getLineBottom(i) - staticLayout.getLineTop(i)
                    val targetCanvas = checkPageOverflow(lineHeight.toFloat())
                    
                    val baselineY = currentY - paint.fontMetrics.ascent
                    targetCanvas.drawText(lineStr, leftPadding, baselineY, paint)
                    currentY += lineHeight
                }
                currentY += 5f // Small paragraph distance multiplier
            }
        }

        // 1. PAPER TITLE
        val titleLayout = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            StaticLayout.Builder.obtain(paper.title.ifBlank { "MANUSCRITO PRELIMINAR" }, 0, paper.title.ifBlank { "MANUSCRITO PRELIMINAR" }.length, titlePaint, contentWidth.toInt())
                .setAlignment(Layout.Alignment.ALIGN_CENTER)
                .build()
        } else {
            @Suppress("DEPRECATION")
            StaticLayout(paper.title.ifBlank { "MANUSCRITO PRELIMINAR" }, titlePaint, contentWidth.toInt(), Layout.Alignment.ALIGN_CENTER, 1f, 0f, false)
        }
        
        canvas = checkPageOverflow(titleLayout.height.toFloat())
        canvas.save()
        canvas.translate(margin, currentY)
        titleLayout.draw(canvas)
        canvas.restore()
        currentY += titleLayout.height + 12f

        // 2. SUBTITLE / STUDY FIELD & JOURNAL
        val metadataString = "${paper.fieldOfStudy.ifBlank { "Campo Académico" }} | Formato: ${paper.type}"
        val subLayout = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            StaticLayout.Builder.obtain(metadataString, 0, metadataString.length, subtitlePaint, contentWidth.toInt())
                .setAlignment(Layout.Alignment.ALIGN_CENTER)
                .build()
        } else {
            @Suppress("DEPRECATION")
            StaticLayout(metadataString, subtitlePaint, contentWidth.toInt(), Layout.Alignment.ALIGN_CENTER, 1.15f, 0f, false)
        }
        canvas = checkPageOverflow(subLayout.height.toFloat())
        canvas.save()
        canvas.translate(margin, currentY)
        subLayout.draw(canvas)
        canvas.restore()
        currentY += subLayout.height + 15f

        // Solid top separator for abstract block
        canvas = checkPageOverflow(2f)
        canvas.drawLine(margin, currentY, pageWidth - margin, currentY, decoratorPaint)
        currentY += 10f

        // 3. ABSTRACT
        canvas = checkPageOverflow(15f)
        val absLabel = "RESUMEN"
        val absLabelX = (pageWidth - boldLabelPaint.measureText(absLabel)) / 2f
        canvas.drawText(absLabel, absLabelX, currentY - boldLabelPaint.fontMetrics.ascent, boldLabelPaint)
        currentY += 15f

        // Print wrapped Abstract with indentation
        val absIndent = 30f
        val absContentWidth = contentWidth - (absIndent * 2)
        drawWrappedText(
            text = paper.abstractText.ifBlank { "Este manuscrito científico no cuenta con datos de resumen redactados aún." },
            paint = textPaint,
            width = absContentWidth.toInt(),
            leftPadding = margin + absIndent
        )
        currentY += 6f

        // 4. KEYWORDS
        if (paper.keywords.isNotBlank()) {
            canvas = checkPageOverflow(12f)
            val keywordsPrompt = "Palabras Clave: "
            val keysFull = keywordsPrompt + paper.keywords
            drawWrappedText(
                text = keysFull,
                paint = textPaint,
                width = absContentWidth.toInt(),
                leftPadding = margin + absIndent
            )
        }
        currentY += 8f

        // Solid bottom separator for abstract block
        canvas = checkPageOverflow(2f)
        canvas.drawLine(margin, currentY, pageWidth - margin, currentY, decoratorPaint)
        currentY += 16f

        // 5. BODY SECTIONS LIST
        val sections = listOf(
            "I. INTRODUCCIÓN" to paper.introduction.ifBlank { "Este apartado representa la inserción inicial, abordando la relevancia, motivación y objetivos principales de la investigación." },
            "II. METODOLOGÍA" to paper.methodology.ifBlank { "Se detallan de manera concisa el marco metodológico, los algoritmos aplicados, configuraciones técnicas y de modelamiento." },
            "III. RESULTADOS Y DISCUSIÓN" to paper.resultsAndEvaluation.ifBlank { "Exposión de los resultados experimentales logrados mediante simulaciones, métricas críticas de error e índices comparativos de efectividad." },
            "IV. CONCLUSIONES" to paper.conclusion.ifBlank { "Análisis reflexivo sobre la validez de las hipótesis planteadas y las líneas de acción de escalamiento para estudios futuros." }
        )

        sections.forEach { (heading, body) ->
            // Print Section Heading
            canvas = checkPageOverflow(26f)
            canvas.drawText(heading, margin, currentY - sectionPaint.fontMetrics.ascent, sectionPaint)
            currentY += 18f
            
            // Print Section Body (wrapped in full content width)
            drawWrappedText(
                text = body,
                paint = textPaint,
                width = contentWidth.toInt(),
                leftPadding = margin
            )
            currentY += 12f
        }

        // 6. REFERENCES SECTION
        canvas = checkPageOverflow(26f)
        canvas.drawText("V. REFERENCIAS BIBLIOGRÁFICAS", margin, currentY - sectionPaint.fontMetrics.ascent, sectionPaint)
        currentY += 18f

        if (paper.referencesText.isNotBlank()) {
            val refsList = paper.referencesText.split("\n").filter { it.isNotBlank() }
            refsList.forEachIndexed { i, ref ->
                val refLine = "[${i + 1}] $ref"
                drawWrappedText(
                    text = refLine,
                    paint = textPaint,
                    width = contentWidth.toInt(),
                    leftPadding = margin
                )
                currentY += 4f
            }
        } else {
            drawWrappedText(
                text = "[1] Referencia modelo de citación cientifica indexada.",
                paint = textPaint,
                width = contentWidth.toInt(),
                leftPadding = margin
            )
        }

        // Seal the final page
        drawHeaderAndFooter(canvas, pageNumber)
        pdfDocument.finishPage(page)

        // Save and share via Android FileProvider
        val pdfFileName = "Draft_${paper.id}_" + (paper.title.take(15).replace("[^a-zA-Z0-9]".toRegex(), "_")) + ".pdf"
        try {
            val cacheFile = File(context.cacheDir, pdfFileName)
            val outputStream = FileOutputStream(cacheFile)
            pdfDocument.writeTo(outputStream)
            outputStream.flush()
            outputStream.close()

            pdfDocument.close()

            // Prepare sharing URI using dynamic application identity FileProvider
            val fileUri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                cacheFile
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, fileUri)
                putExtra(Intent.EXTRA_SUBJECT, "PDF Científico: ${paper.title}")
                putExtra(Intent.EXTRA_TEXT, "Comparto borrador formal en PDF del paper: '${paper.title}' generado de manera automatizada.")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            context.startActivity(Intent.createChooser(shareIntent, "Exportar y Guardar PDF"))
        } catch (e: Exception) {
            pdfDocument.close()
            Toast.makeText(context, "Error exportando PDF: ${e.message}", Toast.LENGTH_LONG).show()
        }
    }
}
